/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author LUISM
 */
public class Interfaz_AgregaUsu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_AgregaUsu
     */
    public Interfaz_AgregaUsu() {
        initComponents();
        this.setSize(630, 561);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSubT = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jspTitulo = new javax.swing.JSeparator();
        lblSubT1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblID_Pro = new javax.swing.JLabel();
        txtNombreCom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblProvedor = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jspNombre = new javax.swing.JSeparator();
        jspID_Prod = new javax.swing.JSeparator();
        jspDescripcion = new javax.swing.JSeparator();
        txtConfirContra = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        cmbTipoUSU = new javax.swing.JComboBox<>();
        lblStock = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        jspStock = new javax.swing.JSeparator();
        btnRegresar = new javax.swing.JButton();
        txtNombreUSU = new javax.swing.JTextField();
        jspID_Prod1 = new javax.swing.JSeparator();
        jspStock1 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblSubT.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblSubT.setForeground(new java.awt.Color(66, 65, 70));
        lblSubT.setText("Nuevo Usuario");
        getContentPane().add(lblSubT);
        lblSubT.setBounds(20, 10, 210, 30);

        lblTitulo.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(66, 65, 70));
        lblTitulo.setText("Campos Obligatorios *");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(210, 10, 210, 30);

        jspTitulo.setBackground(new java.awt.Color(99, 99, 101));
        jspTitulo.setForeground(new java.awt.Color(99, 99, 101));
        jspTitulo.setDoubleBuffered(true);
        jspTitulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jspTitulo.setMinimumSize(new java.awt.Dimension(650, 5));
        jspTitulo.setPreferredSize(new java.awt.Dimension(0, 5));
        getContentPane().add(jspTitulo);
        jspTitulo.setBounds(0, 40, 620, 10);

        lblSubT1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblSubT1.setForeground(new java.awt.Color(66, 65, 70));
        lblSubT1.setText("Información:");
        getContentPane().add(lblSubT1);
        lblSubT1.setBounds(80, 50, 130, 30);

        btnGuardar.setBackground(new java.awt.Color(78, 193, 188));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Guardar.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(530, 0, 90, 40);

        lblID_Pro.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblID_Pro.setForeground(new java.awt.Color(66, 65, 70));
        lblID_Pro.setText("Nombre Completo: *");
        getContentPane().add(lblID_Pro);
        lblID_Pro.setBounds(130, 80, 150, 30);

        txtNombreCom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNombreCom.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreCom.setBorder(null);
        txtNombreCom.setOpaque(false);
        txtNombreCom.setSelectedTextColor(new java.awt.Color(66, 65, 70));
        getContentPane().add(txtNombreCom);
        txtNombreCom.setBounds(270, 90, 220, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/UserName_100px.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 50, 100, 100);

        lblProvedor.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblProvedor.setForeground(new java.awt.Color(66, 65, 70));
        lblProvedor.setText("Nombre Usuario: *");
        getContentPane().add(lblProvedor);
        lblProvedor.setBounds(130, 130, 130, 30);

        lblNombre1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(66, 65, 70));
        lblNombre1.setText("Contraseña: *");
        getContentPane().add(lblNombre1);
        lblNombre1.setBounds(130, 170, 100, 30);

        txtContraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(102, 102, 102));
        txtContraseña.setBorder(null);
        txtContraseña.setOpaque(false);
        txtContraseña.setSelectedTextColor(new java.awt.Color(66, 65, 70));
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(270, 180, 170, 22);

        lblDescripcion.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(66, 65, 70));
        lblDescripcion.setText("Confirmar ");
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(130, 210, 80, 30);

        jspNombre.setBackground(new java.awt.Color(99, 99, 101));
        jspNombre.setForeground(new java.awt.Color(99, 99, 101));
        jspNombre.setDoubleBuffered(true);
        getContentPane().add(jspNombre);
        jspNombre.setBounds(270, 200, 170, 20);

        jspID_Prod.setBackground(new java.awt.Color(99, 99, 101));
        jspID_Prod.setForeground(new java.awt.Color(99, 99, 101));
        jspID_Prod.setDoubleBuffered(true);
        getContentPane().add(jspID_Prod);
        jspID_Prod.setBounds(270, 110, 220, 20);

        jspDescripcion.setBackground(new java.awt.Color(99, 99, 101));
        jspDescripcion.setForeground(new java.awt.Color(99, 99, 101));
        jspDescripcion.setDoubleBuffered(true);
        getContentPane().add(jspDescripcion);
        jspDescripcion.setBounds(270, 260, 170, 20);

        txtConfirContra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtConfirContra.setForeground(new java.awt.Color(102, 102, 102));
        txtConfirContra.setBorder(null);
        txtConfirContra.setOpaque(false);
        txtConfirContra.setSelectedTextColor(new java.awt.Color(66, 65, 70));
        getContentPane().add(txtConfirContra);
        txtConfirContra.setBounds(270, 240, 170, 22);

        lblPrecio.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(66, 65, 70));
        lblPrecio.setText("Contraseña:");
        getContentPane().add(lblPrecio);
        lblPrecio.setBounds(130, 230, 110, 30);

        lblCosto.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(66, 65, 70));
        lblCosto.setText("Tipo de Usuario:");
        getContentPane().add(lblCosto);
        lblCosto.setBounds(130, 290, 130, 30);

        lblCategoria.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(66, 65, 70));
        lblCategoria.setText("Telefono:");
        getContentPane().add(lblCategoria);
        lblCategoria.setBounds(130, 340, 80, 40);

        cmbTipoUSU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbTipoUSU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "G", "U" }));
        cmbTipoUSU.setOpaque(false);
        getContentPane().add(cmbTipoUSU);
        cmbTipoUSU.setBounds(270, 290, 50, 28);

        lblStock.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblStock.setForeground(new java.awt.Color(66, 65, 70));
        lblStock.setText("Domicilio:");
        getContentPane().add(lblStock);
        lblStock.setBounds(130, 390, 80, 30);

        txtDomicilio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDomicilio.setForeground(new java.awt.Color(102, 102, 102));
        txtDomicilio.setBorder(null);
        txtDomicilio.setOpaque(false);
        txtDomicilio.setSelectedTextColor(new java.awt.Color(66, 65, 70));
        getContentPane().add(txtDomicilio);
        txtDomicilio.setBounds(270, 390, 170, 22);

        jspStock.setBackground(new java.awt.Color(99, 99, 101));
        jspStock.setForeground(new java.awt.Color(99, 99, 101));
        jspStock.setDoubleBuffered(true);
        getContentPane().add(jspStock);
        jspStock.setBounds(270, 410, 170, 20);

        btnRegresar.setBackground(new java.awt.Color(255, 153, 0));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/regreso-NegroF.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(430, 460, 160, 45);

        txtNombreUSU.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNombreUSU.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreUSU.setBorder(null);
        txtNombreUSU.setOpaque(false);
        txtNombreUSU.setSelectedTextColor(new java.awt.Color(66, 65, 70));
        getContentPane().add(txtNombreUSU);
        txtNombreUSU.setBounds(270, 130, 220, 22);

        jspID_Prod1.setBackground(new java.awt.Color(99, 99, 101));
        jspID_Prod1.setForeground(new java.awt.Color(99, 99, 101));
        jspID_Prod1.setDoubleBuffered(true);
        getContentPane().add(jspID_Prod1);
        jspID_Prod1.setBounds(270, 150, 220, 20);

        jspStock1.setBackground(new java.awt.Color(99, 99, 101));
        jspStock1.setForeground(new java.awt.Color(99, 99, 101));
        jspStock1.setDoubleBuffered(true);
        getContentPane().add(jspStock1);
        jspStock1.setBounds(270, 370, 170, 20);

        txtTelefono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono.setBorder(null);
        txtTelefono.setOpaque(false);
        txtTelefono.setSelectedTextColor(new java.awt.Color(66, 65, 70));
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(270, 350, 170, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_AgregaUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_AgregaUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_AgregaUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_AgregaUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_AgregaUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JComboBox<String> cmbTipoUSU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jspDescripcion;
    private javax.swing.JSeparator jspID_Prod;
    private javax.swing.JSeparator jspID_Prod1;
    private javax.swing.JSeparator jspNombre;
    private javax.swing.JSeparator jspStock;
    private javax.swing.JSeparator jspStock1;
    private javax.swing.JSeparator jspTitulo;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblID_Pro;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProvedor;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblSubT;
    private javax.swing.JLabel lblSubT1;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JTextField txtConfirContra;
    public javax.swing.JTextField txtContraseña;
    public javax.swing.JTextField txtDomicilio;
    public javax.swing.JTextField txtNombreCom;
    public javax.swing.JTextField txtNombreUSU;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
