/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author INOVATEC
 */
public class Interfaz_DevolverProducto extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_DevolverProducto
     */
    public Interfaz_DevolverProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_IdProducto = new javax.swing.JLabel();
        btn_Confirmar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        lbl_IdVenta = new javax.swing.JLabel();
        txt_IdProducto = new javax.swing.JTextField();
        txt_IdVenta = new javax.swing.JTextField();
        lbl_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_IdProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_IdProducto.setText("Código de Producto:");
        getContentPane().add(lbl_IdProducto);
        lbl_IdProducto.setBounds(2, 23, 170, 22);

        btn_Confirmar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Confirmar.setText("Confirmar");
        getContentPane().add(btn_Confirmar);
        btn_Confirmar.setBounds(10, 110, 165, 50);

        btn_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Cancelar.setText("Cancelar");
        getContentPane().add(btn_Cancelar);
        btn_Cancelar.setBounds(190, 110, 130, 50);

        lbl_IdVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_IdVenta.setText("Código de Venta:");
        getContentPane().add(lbl_IdVenta);
        lbl_IdVenta.setBounds(30, 70, 140, 22);

        txt_IdProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_IdProducto);
        txt_IdProducto.setBounds(183, 20, 140, 28);

        txt_IdVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_IdVenta);
        txt_IdVenta.setBounds(180, 70, 140, 28);

        lbl_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/src_CerrarCaja/bluetriangles.png"))); // NOI18N
        getContentPane().add(lbl_Background);
        lbl_Background.setBounds(0, 0, 340, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_DevolverProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_DevolverProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_DevolverProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_DevolverProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_DevolverProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Cancelar;
    public javax.swing.JButton btn_Confirmar;
    private javax.swing.JLabel lbl_Background;
    private javax.swing.JLabel lbl_IdProducto;
    private javax.swing.JLabel lbl_IdVenta;
    public javax.swing.JTextField txt_IdProducto;
    public javax.swing.JTextField txt_IdVenta;
    // End of variables declaration//GEN-END:variables
}
