/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author darie
 */
public class Interfaz_CerrarCaja extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_CerrarCaja
     */
    public Interfaz_CerrarCaja() {
        initComponents();
        this.setLocation(283,184);
        lblFecha.setText(fechaSystem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spin_10 = new javax.swing.JSpinner();
        spin_5 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        spin_2 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spin_1 = new javax.swing.JSpinner();
        btn_CorteCaja = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCajaFondo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblGanancias = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        spin_500 = new javax.swing.JSpinner();
        spin_200 = new javax.swing.JSpinner();
        spin_100 = new javax.swing.JSpinner();
        spin_50 = new javax.swing.JSpinner();
        spin_20 = new javax.swing.JSpinner();
        lblFecha = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setTitle("Corte de Caja");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon_Empresa_Transparente.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(624, 354));
        setMinimumSize(new java.awt.Dimension(624, 354));
        getContentPane().setLayout(null);

        spin_10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin_10.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spin_10);
        spin_10.setBounds(140, 110, 54, 24);

        spin_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin_5.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spin_5);
        spin_5.setBounds(230, 20, 54, 24);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("2:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 70, 13, 17);

        spin_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin_2.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spin_2);
        spin_2.setBounds(230, 70, 54, 24);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("1:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 120, 13, 17);

        spin_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin_1.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spin_1);
        spin_1.setBounds(230, 110, 54, 24);

        btn_CorteCaja.setText("Corte de Caja!");
        btn_CorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CorteCajaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CorteCaja);
        btn_CorteCaja.setBounds(10, 160, 280, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("500:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 29, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Caja Fondo:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(320, 60, 130, 27);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("200:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 29, 17);

        lblCajaFondo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblCajaFondo.setText("-");
        getContentPane().add(lblCajaFondo);
        lblCajaFondo.setBounds(470, 60, 130, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("20:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 70, 21, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Ganancias:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(320, 100, 120, 27);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("10:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 120, 21, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("100:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 120, 29, 17);

        lblGanancias.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblGanancias.setText("-");
        getContentPane().add(lblGanancias);
        lblGanancias.setBounds(470, 110, 130, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("50:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 20, 21, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("5:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 20, 13, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Total:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 10, 70, 27);

        lblTotal.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTotal.setText("-");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(470, 20, 130, 22);

        spin_500.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin_500.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spin_500);
        spin_500.setBounds(50, 20, 54, 24);

        spin_200.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin_200.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spin_200);
        spin_200.setBounds(50, 70, 54, 24);

        spin_100.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin_100.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spin_100);
        spin_100.setBounds(50, 110, 54, 24);

        spin_50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin_50.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spin_50);
        spin_50.setBounds(140, 20, 54, 24);

        spin_20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin_20.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spin_20);
        spin_20.setBounds(140, 70, 54, 24);

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblFecha);
        lblFecha.setBounds(480, 170, 110, 30);

        lblfecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblfecha.setText("Fecha:");
        lblfecha.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblfecha);
        lblfecha.setBounds(390, 160, 70, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/src_CerrarCaja/Separator.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, -30, 120, 312);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CorteCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CorteCajaActionPerformed
    
    private static String fechaSystem(){
      Date fecha=new Date();
      SimpleDateFormat formatoF= new SimpleDateFormat("dd/MM/YYYY");
      return formatoF.format(fecha);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_CorteCaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblCajaFondo;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblGanancias;
    public javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblfecha;
    public javax.swing.JSpinner spin_1;
    public javax.swing.JSpinner spin_10;
    public javax.swing.JSpinner spin_100;
    public javax.swing.JSpinner spin_2;
    public javax.swing.JSpinner spin_20;
    public javax.swing.JSpinner spin_200;
    public javax.swing.JSpinner spin_5;
    public javax.swing.JSpinner spin_50;
    public javax.swing.JSpinner spin_500;
    // End of variables declaration//GEN-END:variables
}
